<?xml version="1.0" encoding="utf-8"?>
      <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" ></meta>
        <meta http-equiv="Expires" content="0" />
        <title>scala/xml/include/XIncludeException.scala</title>
        <script type="text/javascript" src="../../../jquery-all.js"></script>
        <script type="text/javascript" src="../../../linked.js"></script>
        <link rel="stylesheet" type="text/css" href="../../../style.css" title="Style"></link>
    </head>
    <body>
        <pre>
<span class="comment">/*                     __                                               *\
**     ________ ___   / /  ___     Scala API                            **
**    / __/ __// _ | / /  / _ |    (c) 2002-2011, LAMP/EPFL             **
**  __\ \/ /__/ __ |/ /__/ __ |    http://scala-lang.org/               **
** /____/\___/_/ |_/____/_/ | |                                         **
**                          |/                                          **
\*                                                                      */</span>


<span class="keyword">package</span> scala.xml
<span class="keyword">package</span> include

<span class="comment">/**
 * &lt;p&gt;
 * &lt;code&gt;XIncludeException&lt;/code&gt; is the generic superclass
 * for all checked exceptions that may be thrown as a result
 * of a violation of XInclude's rules.
 * &lt;/p&gt;
 * &lt;p&gt;
 * Constructs an &lt;code&gt;XIncludeException&lt;/code&gt; with the specified detail
 * message. The error message string &lt;code&gt;message&lt;/code&gt; can later be
 * retrieved by the &lt;code&gt;{@link java.lang.Throwable#getMessage}&lt;/code&gt;
 * method of class &lt;code&gt;java.lang.Throwable&lt;/code&gt;.
 * &lt;/p&gt;
 *
 * @param   message   the detail message.
 */</span>
<span class="keyword">class</span> <a title="class XIncludeException extends java.lang.Exception with ScalaObject" id="24365">XIncludeException</a><a href="../../ScalaObject.scala.html#456" title="ScalaObject" class="delimiter">(</a><a title="String" id="499773">message</a>: <span title="String">String</span><span class="delimiter">)</span> <span class="keyword">extends</span> <a href="../../package.scala.html#24942" title="java.lang.Exception">Exception</a><span class="delimiter">(</span><a href="#499773" title="String">message</a><span class="delimiter">)</span> <span class="delimiter">{</span>

  <span class="comment">/**
   * uses &lt;code&gt;null&lt;/code&gt; as its error detail message.
   */</span>
  <span class="keyword">def</span> <a title="()scala.xml.include.XIncludeException" id="499756" class="keyword">this</a><span class="delimiter">(</span><span class="delimiter">)</span> = <a href="#24365" title="XIncludeException.this.type" class="keyword">this</a><span class="delimiter">(</span><span title="Null(null)" class="keyword">null</span><span class="delimiter">)</span>

  <span class="keyword">private</span> <span class="keyword">var</span> <a title="Throwable" id="499758">rootCause</a>: <span title="Throwable">Throwable</span> = <span title="Null(null)" class="keyword">null</span>

  <span class="comment">/**
   * When an &lt;code&gt;IOException&lt;/code&gt;, &lt;code&gt;MalformedURLException&lt;/code&gt; 
   * or other generic exception is thrown while processing an XML document
   * for XIncludes, it is customarily replaced
   * by some form of &lt;code&gt;XIncludeException&lt;/code&gt;.  
   * This method allows you to store the original exception.
   *
   * @param   nestedException   the underlying exception which 
   * caused the XIncludeException to be thrown
   */</span>
  <span class="keyword">def</span> <a title="(nestedException: Throwable)Unit" id="499760">setRootCause</a><span class="delimiter">(</span><a title="Throwable" id="499828">nestedException</a>: <span title="Throwable">Throwable</span> <span class="delimiter">)</span> <span class="delimiter">{</span>
    <a href="#24365" title="XIncludeException.this.type" class="keyword">this</a>.<a href="#499758" title="(x$1: Throwable)Unit">rootCause</a> = <a href="#499828" title="Throwable">nestedException</a>
  <span class="delimiter">}</span>

  <span class="comment">/**
   * When an &lt;code&gt;IOException&lt;/code&gt;, &lt;code&gt;MalformedURLException&lt;/code&gt; 
   * or other generic exception is thrown while processing an XML document
   * for XIncludes, it is customarily replaced
   * by some form of &lt;code&gt;XIncludeException&lt;/code&gt;.  
   * This method allows you to retrieve the original exception.
   * It returns null if no such exception caused this &lt;code&gt;XIncludeException&lt;/code&gt;.
   *
   * @return Throwable   the underlying exception which caused the
   *                     &lt;code&gt;XIncludeException&lt;/code&gt; to be thrown
   */</span>
  <span class="keyword">def</span> <a title="()Throwable" id="499761">getRootCause</a><span class="delimiter">(</span><span class="delimiter">)</span>: <span title="Throwable">Throwable</span> = <a href="#24365" title="XIncludeException.this.type" class="keyword">this</a>.<a href="#499758" title="=&gt; Throwable">rootCause</a>
  
<span class="delimiter">}</span>

        </pre>
    </body>
</html>